language: node_js
services:
  - elasticsearch
node_js:
  - "0.10"
env:
  secure: "PRaWdR5cSKEaf1sETbMS1yKxOROHo46dHknupu/2+TJ4QQ4xqGhpFtYtcga48L15vOm7RbGdwT3m9Ojv5gWtriBW16EoTZav+MIDJgKwOdb16WEurwdPZVZY41FTZt2O0j9c7JgYud3jPF1eHxYrBocmpeGlstvcCkOPcljOGZ0="
